services:
  database:
    image: postgres:17.2
    container_name: encurtador-de-link-db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=encurtador_de_link_db
    
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db: