springdoc:
  swagger-ui:
    path: /docs/ui
  api-docs:
    path: /docs
spring:
    application:
        name: fernando-encurtador-de-link
    graphql:
        schema:
            file-extensions: 
                - gql
        graphiql:
            enabled: true
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update